# Generated by Django 4.1.5 on 2023-01-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='normal', max_length=15, verbose_name='Type'),
        ),
    ]
